run:
  timeout: 2m

linters-settings:
  govet:
    enable-all: true
  goimports:
    local-prefixes: github.com/ackerr/lab

linters:
  enable:
    - bodyclose
    - dupl
    - exportloopref
    - goconst
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - govet
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
