before:
  hooks:
    - go mod tidy
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm
    - '386'
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - 'Merge pull request'
    - 'Bump version'
brews:
- tap:
    owner: Ackerr
    name: homebrew-tap
  description: A cli tool with gitlab.
  homepage: "https://github.com/Ackerr/lab"
  test: |
    system "#{bin}/lab -v"
  install: |
    bin.install "lab"

scoop:
  bucket:
    owner: Ackerr
    name: scoop-bucket
  homepage: "https://github.com/Ackerr/lab"
  persist:
    - "data"
    - "config.toml"
