name: CI
on:
  push:
    branches: [master]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Dependency
      run: make install

    - name: Lint
      run: |-
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        golint -set_exit_status $(go list ./...)
        go vet ./...

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Release
      uses: goreleaser/goreleaser-action@master
      with:
        args: release --snapshot --skip-publish --rm-dist
